### PR TITLE
Tweak to setup.py to allow setuptools development mode

### PR DESCRIPTION
**Pull request by DanHickstein**
This is needed to allow `python setup.py develop` to work. 

`python setup.py install` should be unaffected.

### CODE REVIEW

**Comment by ycasg** [comment]
That's odd, it seemed to work when I tested it.

**Comment by DanHickstein** [comment]
Yeah, I was confused for a while too. Before this change it installs just fine in development mode, but when you try to `import pynlo` it cannot find it. You probably already had pynlo installed previously, so you were likely still abel to import it, though if you looked at `pynlo.__file__` it would have been in the site-packages directory for your python distribution and not the local version of pynlo.

**Comment by ycasg** [comment]
I've actually done something even worse, and have the development path added to my python path. Thanks for installing it correctly and fixing this.

**Comment by DanHickstein** [comment]
Yes, this is the horror that `setup.py develop` saves me from. You can have the stable version installed, `python setup.py develop` the cutting edge version, hack away, then `python setup.py develop --uninstall` when you want to retreat to normalcy.

**Pull request merged**
